// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum DatePartSelector
{
	year("b092d327-83f7-4beb-a5e8-469498fb4cf9"),
	month("00cfc830-e5be-440e-bd93-b629920244dc"),
	day("4db553d6-2850-46c1-98ff-83744c466a7e");

	private final java.lang.String i18nCaptionKey;
	
	private DatePartSelector(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
