// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("970c54ad-a412-492b-ba65-e7b4837d99b0"),
	Debug("5f1f4608-4b32-4a1c-99d2-a48c7bf161e1"),
	Info("b3982627-b3c5-47f7-b3c5-bbdbe34b7de7"),
	Warning("5a2f3342-2082-448c-84ab-af969dd1a2ab"),
	Error("6a732d9f-2d16-4db5-b527-06ca63d5579c"),
	Critical("34387230-c726-402c-a11c-69603329afd2");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
