// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("54d02dd1-3346-4b11-aa03-4ceed19db33f"),
	FORMATTING("5b40de9e-290e-429d-9977-6ce198373c85"),
	IMAGES("d13a5709-4d42-4c84-b2c7-01b70865ad67"),
	LINKS("6e003f7b-5911-4b6b-ab20-46b9b785eebe"),
	STYLES("37ade6ea-bbcc-4acc-8ef7-09f9746f5913"),
	TABLES("9dc4d5d3-9ed9-4c2c-aded-48be3413f62e");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
