// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("2f98e5f9-c9f5-4a13-b80c-147204107f62"),
	ISO_8859_1("d464503c-3e79-435f-9cea-32d2977e76ba"),
	UTF_8("6f3a055a-e1d5-4b0c-a8f4-a2a301f7ce19"),
	UTF_16BE("4ca03f42-d8a2-4e8a-8e25-edc94f31d44a"),
	UTF_16LE("334f678e-e60c-45ff-9fac-22fe47eb4e19"),
	UTF_16("867d76cc-4024-4964-980d-4758a94ee1ee");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
