// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies;

public enum EnumForSample
{
	Red("249f8b69-f89d-4e0b-b60a-3f96d9792f53"),
	Green("dc3386bc-d40e-4542-aa6d-78faa6e467f7");

	private final java.lang.String i18nCaptionKey;
	
	private EnumForSample(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
