// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies;

public class OrderItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxDBUnit.OrderItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Count("Count"),
		Amount("Amount"),
		OrderItem_Item("MxDBUnit.OrderItem_Item"),
		OrderItem_Order("MxDBUnit.OrderItem_Order");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderItemMendixObject)
	{
		if (orderItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderItemMendixObject = orderItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxdbunit.proxies.OrderItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxdbunit.proxies.OrderItem(context, mendixObject);
	}

	public static mxdbunit.proxies.OrderItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxdbunit.proxies.OrderItem.initialize(context, mendixObject);
	}

	public static java.util.List<mxdbunit.proxies.OrderItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxdbunit.proxies.OrderItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderItem_Item
	 */
	public final mxdbunit.proxies.Item getOrderItem_Item() throws com.mendix.core.CoreException
	{
		return getOrderItem_Item(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderItem_Item
	 * @throws com.mendix.core.CoreException
	 */
	public final mxdbunit.proxies.Item getOrderItem_Item(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxdbunit.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderItem_Item.toString());
		if (identifier != null) {
			result = mxdbunit.proxies.Item.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderItem_Item
	 * @param orderitem_item
	 */
	public final void setOrderItem_Item(mxdbunit.proxies.Item orderitem_item)
	{
		setOrderItem_Item(getContext(), orderitem_item);
	}

	/**
	 * Set value of OrderItem_Item
	 * @param context
	 * @param orderitem_item
	 */
	public final void setOrderItem_Item(com.mendix.systemwideinterfaces.core.IContext context, mxdbunit.proxies.Item orderitem_item)
	{
		if (orderitem_item == null) {
			getMendixObject().setValue(context, MemberNames.OrderItem_Item.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderItem_Item.toString(), orderitem_item.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderItem_Order
	 */
	public final mxdbunit.proxies.Order getOrderItem_Order() throws com.mendix.core.CoreException
	{
		return getOrderItem_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderItem_Order
	 * @throws com.mendix.core.CoreException
	 */
	public final mxdbunit.proxies.Order getOrderItem_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxdbunit.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderItem_Order.toString());
		if (identifier != null) {
			result = mxdbunit.proxies.Order.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderItem_Order
	 * @param orderitem_order
	 */
	public final void setOrderItem_Order(mxdbunit.proxies.Order orderitem_order)
	{
		setOrderItem_Order(getContext(), orderitem_order);
	}

	/**
	 * Set value of OrderItem_Order
	 * @param context
	 * @param orderitem_order
	 */
	public final void setOrderItem_Order(com.mendix.systemwideinterfaces.core.IContext context, mxdbunit.proxies.Order orderitem_order)
	{
		if (orderitem_order == null) {
			getMendixObject().setValue(context, MemberNames.OrderItem_Order.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderItem_Order.toString(), orderitem_order.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxdbunit.proxies.OrderItem that = (mxdbunit.proxies.OrderItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
