// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies;

public class Order implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxDBUnit.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		OrderDate("OrderDate"),
		TotalAtamount("TotalAtamount"),
		Order_Customer("MxDBUnit.Order_Customer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Order(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Order(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxdbunit.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxdbunit.proxies.Order(context, mendixObject);
	}

	public static mxdbunit.proxies.Order load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxdbunit.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<mxdbunit.proxies.Order> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxdbunit.proxies.Order.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.Long getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.Long getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.Long ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of TotalAtamount
	 */
	public final java.math.BigDecimal getTotalAtamount()
	{
		return getTotalAtamount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalAtamount
	 */
	public final java.math.BigDecimal getTotalAtamount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalAtamount.toString());
	}

	/**
	 * Set value of TotalAtamount
	 * @param totalatamount
	 */
	public final void setTotalAtamount(java.math.BigDecimal totalatamount)
	{
		setTotalAtamount(getContext(), totalatamount);
	}

	/**
	 * Set value of TotalAtamount
	 * @param context
	 * @param totalatamount
	 */
	public final void setTotalAtamount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalatamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalAtamount.toString(), totalatamount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Customer
	 */
	public final mxdbunit.proxies.Customer getOrder_Customer() throws com.mendix.core.CoreException
	{
		return getOrder_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final mxdbunit.proxies.Customer getOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxdbunit.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_Customer.toString());
		if (identifier != null) {
			result = mxdbunit.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_Customer
	 * @param order_customer
	 */
	public final void setOrder_Customer(mxdbunit.proxies.Customer order_customer)
	{
		setOrder_Customer(getContext(), order_customer);
	}

	/**
	 * Set value of Order_Customer
	 * @param context
	 * @param order_customer
	 */
	public final void setOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context, mxdbunit.proxies.Customer order_customer)
	{
		if (order_customer == null) {
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_Customer.toString(), order_customer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxdbunit.proxies.Order that = (mxdbunit.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
