// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies;

public class TestExtendedEntity2 extends mxdbunit.proxies.TestBaseEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxDBUnit.TestExtendedEntity2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ExtendedAttr2("ExtendedAttr2"),
		BizKeyAttr("BizKeyAttr"),
		BoolAttr("BoolAttr"),
		EnumAttr("EnumAttr");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestExtendedEntity2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestExtendedEntity2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testExtendedEntity2MendixObject)
	{
		super(context, testExtendedEntity2MendixObject);
		if (!testExtendedEntity2MendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxdbunit.proxies.TestExtendedEntity2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxdbunit.proxies.TestExtendedEntity2(context, mendixObject);
	}

	public static mxdbunit.proxies.TestExtendedEntity2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxdbunit.proxies.TestExtendedEntity2.initialize(context, mendixObject);
	}

	public static java.util.List<mxdbunit.proxies.TestExtendedEntity2> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxdbunit.proxies.TestExtendedEntity2.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ExtendedAttr2
	 */
	public final java.lang.String getExtendedAttr2()
	{
		return getExtendedAttr2(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtendedAttr2
	 */
	public final java.lang.String getExtendedAttr2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExtendedAttr2.toString());
	}

	/**
	 * Set value of ExtendedAttr2
	 * @param extendedattr2
	 */
	public final void setExtendedAttr2(java.lang.String extendedattr2)
	{
		setExtendedAttr2(getContext(), extendedattr2);
	}

	/**
	 * Set value of ExtendedAttr2
	 * @param context
	 * @param extendedattr2
	 */
	public final void setExtendedAttr2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extendedattr2)
	{
		getMendixObject().setValue(context, MemberNames.ExtendedAttr2.toString(), extendedattr2);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxdbunit.proxies.TestExtendedEntity2 that = (mxdbunit.proxies.TestExtendedEntity2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
