// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies;

public class TestBaseEntity implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testBaseEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxDBUnit.TestBaseEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BizKeyAttr("BizKeyAttr"),
		BoolAttr("BoolAttr"),
		EnumAttr("EnumAttr");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestBaseEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestBaseEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testBaseEntityMendixObject)
	{
		if (testBaseEntityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testBaseEntityMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testBaseEntityMendixObject = testBaseEntityMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxdbunit.proxies.TestBaseEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("MxDBUnit.TestExtendedEntity1")) {
			return mxdbunit.proxies.TestExtendedEntity1.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("MxDBUnit.TestExtendedEntity2")) {
			return mxdbunit.proxies.TestExtendedEntity2.initialize(context, mendixObject);
		}
		return new mxdbunit.proxies.TestBaseEntity(context, mendixObject);
	}

	public static mxdbunit.proxies.TestBaseEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxdbunit.proxies.TestBaseEntity.initialize(context, mendixObject);
	}

	public static java.util.List<? extends mxdbunit.proxies.TestBaseEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxdbunit.proxies.TestBaseEntity.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of BizKeyAttr
	 */
	public final java.lang.String getBizKeyAttr()
	{
		return getBizKeyAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of BizKeyAttr
	 */
	public final java.lang.String getBizKeyAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BizKeyAttr.toString());
	}

	/**
	 * Set value of BizKeyAttr
	 * @param bizkeyattr
	 */
	public final void setBizKeyAttr(java.lang.String bizkeyattr)
	{
		setBizKeyAttr(getContext(), bizkeyattr);
	}

	/**
	 * Set value of BizKeyAttr
	 * @param context
	 * @param bizkeyattr
	 */
	public final void setBizKeyAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bizkeyattr)
	{
		getMendixObject().setValue(context, MemberNames.BizKeyAttr.toString(), bizkeyattr);
	}

	/**
	 * @return value of BoolAttr
	 */
	public final java.lang.Boolean getBoolAttr()
	{
		return getBoolAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of BoolAttr
	 */
	public final java.lang.Boolean getBoolAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BoolAttr.toString());
	}

	/**
	 * Set value of BoolAttr
	 * @param boolattr
	 */
	public final void setBoolAttr(java.lang.Boolean boolattr)
	{
		setBoolAttr(getContext(), boolattr);
	}

	/**
	 * Set value of BoolAttr
	 * @param context
	 * @param boolattr
	 */
	public final void setBoolAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean boolattr)
	{
		getMendixObject().setValue(context, MemberNames.BoolAttr.toString(), boolattr);
	}

	/**
	 * Get value of EnumAttr
	 * @param enumattr
	 */
	public final mxdbunit.proxies.EnumForSample getEnumAttr()
	{
		return getEnumAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumAttr
	 */
	public final mxdbunit.proxies.EnumForSample getEnumAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumAttr.toString());
		if (obj == null) {
			return null;
		}
		return mxdbunit.proxies.EnumForSample.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumAttr
	 * @param enumattr
	 */
	public final void setEnumAttr(mxdbunit.proxies.EnumForSample enumattr)
	{
		setEnumAttr(getContext(), enumattr);
	}

	/**
	 * Set value of EnumAttr
	 * @param context
	 * @param enumattr
	 */
	public final void setEnumAttr(com.mendix.systemwideinterfaces.core.IContext context, mxdbunit.proxies.EnumForSample enumattr)
	{
		if (enumattr != null) {
			getMendixObject().setValue(context, MemberNames.EnumAttr.toString(), enumattr.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EnumAttr.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testBaseEntityMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxdbunit.proxies.TestBaseEntity that = (mxdbunit.proxies.TestBaseEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
