// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.implementation.DataSetAssertor;
import mxdbunit.implementation.IdentityResolver;
import mxdbunit.implementation.XssfExcelReader;
import mxdbunit.implementation.XssfExcelRowProcessor;

public class AssertListByExcel extends UserAction<java.lang.Void>
{
	private final java.lang.String excelFilePath;
	private final java.lang.String expectedSheetName;
	private final java.util.List<IMendixObject> actualList;

	public AssertListByExcel(
		IContext context,
		java.lang.String _excelFilePath,
		java.lang.String _expectedSheetName,
		java.util.List<IMendixObject> _actualList
	)
	{
		super(context);
		this.excelFilePath = _excelFilePath;
		this.expectedSheetName = _expectedSheetName;
		this.actualList = _actualList;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IdentityResolver identityResolver = (IdentityResolver) getContext().getData().get("IdentityResolver");
		if (identityResolver == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
					"IdentityResolver not found in context. Please run SettupByExcel first.");
		}
		String targetExcelFilePath = excelFilePath != null ? excelFilePath : (String) getContext().getData().get("LastExcelFilePath");
		if (targetExcelFilePath == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Excel file path is not provided and no previous Excel file path found in context.");
		}

		String replacedFilePath = targetExcelFilePath.replace("$HOME", System.getProperty("user.home")).replace("$RESOURCES",
				Core.getConfiguration().getResourcesPath().getAbsolutePath());
		File excelFile = new File(replacedFilePath);

		// Prefix completion (allowing "Expected_Customer" to be accepted when "Customer" is passed)
		final String targetSheetName = this.expectedSheetName.startsWith("Expected_")
				? this.expectedSheetName
				: "Expected_" + this.expectedSheetName;

		List<Map<String, String>> expectedRows = new ArrayList<>();

		// 1. Stream parse only the specified sheets.
		XssfExcelReader.readAllSheets(
				excelFile,
				// Filter only the target sheet
				sheetName -> sheetName.equalsIgnoreCase(targetSheetName),
				// Collection of row data
				new XssfExcelRowProcessor() {
					@Override
					public void processRow(int rowIndex, Map<String, String> rowData) throws Exception {
						if (rowIndex == 1) {
							setupColumnNameMap(rowData);
						}

						Map<String, String> formattedRow = new HashMap<>();
						for (Map.Entry<String, String> entry : rowData.entrySet()) {
							String header = getHeaderName(entry.getKey());
							if (header != null) {
								formattedRow.put(header, entry.getValue());
							}
						}
						expectedRows.add(formattedRow);
					}
				});

		// If the specified sheet does not exist
		if (expectedRows.isEmpty()) {
			throw new IllegalArgumentException(
					"[MxDBUnit Error] Sheet '" + targetSheetName + "' was not found in the provided Excel file.");
		}

		// 2. Calling the common core logic (DataSetAssertor)
		DataSetAssertor.compareTable(
				this.getContext(),
				targetSheetName,
				expectedRows,
				this.actualList != null ? this.actualList : new ArrayList<>(),
				identityResolver);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AssertListByExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
