// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.implementation.IdentityResolver;

/**
 * Perform a batch assertion for entities that have a corresponding "expected results" sheet in the Excel file.
 * All records of the target entity are retrieved as the actual result. Therefore, you must execute `LoadAllFromExcel` with `doClean=true` to clear out any unnecessary data.
 */
public class AssertAllByExcel extends UserAction<java.lang.Void>
{
	private final java.lang.String excelFilePath;

	public AssertAllByExcel(
		IContext context,
		java.lang.String _excelFilePath
	)
	{
		super(context);
		this.excelFilePath = _excelFilePath;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IdentityResolver identityResolver = (IdentityResolver) getContext().getData().get("IdentityResolver");
		if (identityResolver == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("IdentityResolver not found in context. Please run SettupByExcel first.");
		}
		String targetExcelFilePath = excelFilePath != null ? excelFilePath : (String) getContext().getData().get("LastExcelFilePath");
		if (targetExcelFilePath == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Excel file path is not provided and no previous Excel file path found in context.");
		}
		mxdbunit.implementation.ExcelDataAssertor.assertAll(getContext(), targetExcelFilePath, identityResolver);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AssertAllByExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
