// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import java.util.List;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Retrieve the list of loaded objects from the list of non-persistent entity object maps in the context.
 */
public class GetLoadedNPE extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String EntityType;

	public GetLoadedNPE(
		IContext context,
		java.lang.String _entityType
	)
	{
		super(context);
		this.EntityType = _entityType;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map<String, List<IMendixObject>> nonPersistentEntityObjects = (Map<String, List<IMendixObject>>) getContext().getData()
				.get("NonPersistentEntityObjects");
		java.util.List<IMendixObject> result = nonPersistentEntityObjects != null ? nonPersistentEntityObjects.get(EntityType) : null;
		if (result == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
					"Non-persistent entity objects for entity type '" + EntityType + "' not found in context. Please run LoadAllFromExcel first.");
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetLoadedNPE";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
