// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package unittestutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JAV_InsertFromExcel extends UserAction<java.lang.Void>
{
	/** @deprecated use unitTestContext.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __unitTestContext;
	private final unittesting.proxies.UnitTestContext unitTestContext;
	private final java.lang.String excelFilePath;

	public JAV_InsertFromExcel(
		IContext context,
		IMendixObject _unitTestContext,
		java.lang.String _excelFilePath
	)
	{
		super(context);
		this.__unitTestContext = _unitTestContext;
		this.unitTestContext = _unitTestContext == null ? null : unittesting.proxies.UnitTestContext.initialize(getContext(), _unitTestContext);
		this.excelFilePath = _excelFilePath;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAV_InsertFromExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
