// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.implementation.ExcelDataLoader;
import mxdbunit.implementation.IdentityResolver;
import mxdbunit.implementation.TimeZoneResolver;

/**
 * Entities for which preparation data exists in Excel are loaded in bulk and registered in the database.
 * It is also possible to execute this action for each Excel file in order to read data from multiple Excel files within a single test case.
 */
public class LoadAllFromExcel extends UserAction<java.lang.Void>
{
	private final java.lang.String excelFilePath;
	private final java.lang.Boolean doClean;

	public LoadAllFromExcel(
		IContext context,
		java.lang.String _excelFilePath,
		java.lang.Boolean _doClean
	)
	{
		super(context);
		this.excelFilePath = _excelFilePath;
		this.doClean = _doClean;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IdentityResolver identityResolver = (IdentityResolver) getContext().getData().get("IdentityResolver");
		if (identityResolver == null) {
			identityResolver = new IdentityResolver();
			getContext().getData().put("IdentityResolver", identityResolver);
		}
		ExcelDataLoader.loadAll(getContext(), excelFilePath, TimeZoneResolver.getTimeZone(getContext()).toZoneId().getId(), identityResolver, doClean);
		getContext().getData().put("LastExcelFilePath", excelFilePath);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "LoadAllFromExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
