// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.implementation.TimeZoneResolver;

/**
 * Configure the time zone for MxDBUnit that applies at the application scope. This setting is used when no time zone is specified while reading date and time fields from Excel.
 * Please call this from within the "After Startup" process.
 */
public class SetDefaultTimeZoneId extends UserAction<java.lang.Void>
{
	private final java.lang.String TimeZoneId;

	public SetDefaultTimeZoneId(
		IContext context,
		java.lang.String _timeZoneId
	)
	{
		super(context);
		this.TimeZoneId = _timeZoneId;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		TimeZoneResolver.setDefaultTimeZone(TimeZoneId);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetDefaultTimeZoneId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
