// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.integration.ExtDbBridge;

/**
 * For internal databases, the UnitTesting module manages rollback control during test execution, whereas the MxDBUnit module handles this for external databases.
 * By default, the MxDBUnit module initiates transactions and automatically performs rollbacks for all TwoWaySQL external database data sources; however, this action allows you to suppress the initiation of transactions and rollbacks.
 * This setting is controlled on a per-thread basis.
 */
public class SetExtDbRollbackMode extends UserAction<java.lang.Void>
{
	private final java.lang.Boolean ExtDbRollbackMode;

	public SetExtDbRollbackMode(
		IContext context,
		java.lang.Boolean _extDbRollbackMode
	)
	{
		super(context);
		this.ExtDbRollbackMode = _extDbRollbackMode;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExtDbBridge.setExtDbRollbackMode(ExtDbRollbackMode);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetExtDbRollbackMode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
