// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxdbunit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxdbunit.integration.ExtDbBridge;

/**
 * When testing an external DB, you must create a TearDown Microflow in the module containing the test case's Microflow and call the "TearDownMxDBUnit" action. This is a mandatory requirement to prevent deadlocks.
 * To simplify the implementation of individual test case microflows, MxDBUnit performs a "lazy" rollback and connection closure for the preceding test case at the start of the initial "LoadAllFromExcel" action in each test case.
 * Consequently, the "TearDownMxDBUnit" action—called from the "TearDown" microflow—is essential to ensure that the rollback and connection closure for the final test case are executed.
 * See also:
 * https://docs.mendix.com/appstore/modules/unit-testing/#creating-microflow-unit-tests
 */
public class TearDownMxDBUnit extends UserAction<java.lang.Void>
{
	public TearDownMxDBUnit(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExtDbBridge.cleanupAllThreadConnections();
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TearDownMxDBUnit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
