// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittestutil.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the UnitTestUtil module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder insertFromExcelBuilder(
		unittesting.proxies.UnitTestContext _unitTestContext,
		java.lang.String _excelFilePath
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTestUtil.InsertFromExcel");
		builder = builder.withParam("UnitTestContext", _unitTestContext);
		builder = builder.withParam("ExcelFilePath", _excelFilePath);
		return builder;
	}

	public static void insertFromExcel(
		IContext context,
		unittesting.proxies.UnitTestContext _unitTestContext,
		java.lang.String _excelFilePath
	)
	{
		insertFromExcelBuilder(
				_unitTestContext,
				_excelFilePath
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder microflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTestUtil.Microflow");
		return builder;
	}

	public static void microflow(IContext context)
	{
		microflowBuilder().execute(context);
	}
}
