// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxdbunit.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MxDBUnit module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DoSumSample1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.ACT_DoSumSample1");
		return builder;
	}

	public static void aCT_DoSumSample1(IContext context)
	{
		aCT_DoSumSample1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tearDownBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.TearDown");
		return builder;
	}

	public static void tearDown(IContext context)
	{
		tearDownBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_ExtDB_Sample1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.UT_ExtDB_Sample1");
		return builder;
	}

	public static void uT_ExtDB_Sample1(IContext context)
	{
		uT_ExtDB_Sample1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_Sample1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.UT_Sample1");
		return builder;
	}

	public static void uT_Sample1(IContext context)
	{
		uT_Sample1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_Sample2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.UT_Sample2");
		return builder;
	}

	public static void uT_Sample2(IContext context)
	{
		uT_Sample2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_Sample2_2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.UT_Sample2_2");
		return builder;
	}

	public static void uT_Sample2_2(IContext context)
	{
		uT_Sample2_2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_Sample3Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MxDBUnit.UT_Sample3");
		return builder;
	}

	public static void uT_Sample3(IContext context)
	{
		uT_Sample3Builder().execute(context);
	}
}
