// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EmployeeNPE implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeNPEMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmployeeNPE";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NAME("NAME"),
		ADDRESS("ADDRESS"),
		IS_HOGE("IS_HOGE"),
		BIRTH_DATE("BIRTH_DATE");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeNPE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmployeeNPE(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeNPEMendixObject)
	{
		if (employeeNPEMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!employeeNPEMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeNPEMendixObject = employeeNPEMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.EmployeeNPE initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmployeeNPE(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmployeeNPE load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmployeeNPE.initialize(context, mendixObject);
	}

	/**
	 * @return value of NAME
	 */
	public final java.lang.String getNAME()
	{
		return getNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of NAME
	 */
	public final java.lang.String getNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NAME.toString());
	}

	/**
	 * Set value of NAME
	 * @param name
	 */
	public final void setNAME(java.lang.String name)
	{
		setNAME(getContext(), name);
	}

	/**
	 * Set value of NAME
	 * @param context
	 * @param name
	 */
	public final void setNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.NAME.toString(), name);
	}

	/**
	 * @return value of ADDRESS
	 */
	public final java.lang.String getADDRESS()
	{
		return getADDRESS(getContext());
	}

	/**
	 * @param context
	 * @return value of ADDRESS
	 */
	public final java.lang.String getADDRESS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ADDRESS.toString());
	}

	/**
	 * Set value of ADDRESS
	 * @param address
	 */
	public final void setADDRESS(java.lang.String address)
	{
		setADDRESS(getContext(), address);
	}

	/**
	 * Set value of ADDRESS
	 * @param context
	 * @param address
	 */
	public final void setADDRESS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.ADDRESS.toString(), address);
	}

	/**
	 * @return value of IS_HOGE
	 */
	public final java.lang.Boolean getIS_HOGE()
	{
		return getIS_HOGE(getContext());
	}

	/**
	 * @param context
	 * @return value of IS_HOGE
	 */
	public final java.lang.Boolean getIS_HOGE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IS_HOGE.toString());
	}

	/**
	 * Set value of IS_HOGE
	 * @param is_hoge
	 */
	public final void setIS_HOGE(java.lang.Boolean is_hoge)
	{
		setIS_HOGE(getContext(), is_hoge);
	}

	/**
	 * Set value of IS_HOGE
	 * @param context
	 * @param is_hoge
	 */
	public final void setIS_HOGE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean is_hoge)
	{
		getMendixObject().setValue(context, MemberNames.IS_HOGE.toString(), is_hoge);
	}

	/**
	 * @return value of BIRTH_DATE
	 */
	public final java.util.Date getBIRTH_DATE()
	{
		return getBIRTH_DATE(getContext());
	}

	/**
	 * @param context
	 * @return value of BIRTH_DATE
	 */
	public final java.util.Date getBIRTH_DATE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BIRTH_DATE.toString());
	}

	/**
	 * Set value of BIRTH_DATE
	 * @param birth_date
	 */
	public final void setBIRTH_DATE(java.util.Date birth_date)
	{
		setBIRTH_DATE(getContext(), birth_date);
	}

	/**
	 * Set value of BIRTH_DATE
	 * @param context
	 * @param birth_date
	 */
	public final void setBIRTH_DATE(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birth_date)
	{
		getMendixObject().setValue(context, MemberNames.BIRTH_DATE.toString(), birth_date);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeNPEMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmployeeNPE that = (myfirstmodule.proxies.EmployeeNPE) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
