// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the UnitTesting module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestSuite_ResetBuilder(
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_TestSuite_Reset");
		builder = builder.withParam("TestSuite", _testSuite);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_TestSuite_Reset(
		IContext context,
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_TestSuite_ResetBuilder(
				_testSuite,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestSuite_RunBuilder(
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_TestSuite_Run");
		builder = builder.withParam("TestSuite", _testSuite);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_TestSuite_Run(
		IContext context,
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_TestSuite_RunBuilder(
				_testSuite,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestSuite_SelectBuilder(
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_TestSuite_Select");
		builder = builder.withParam("TestSuite", _testSuite);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_TestSuite_Select(
		IContext context,
		unittesting.proxies.TestSuite _testSuite,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_TestSuite_SelectBuilder(
				_testSuite,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTest_BackBuilder(
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTest_Back");
		builder = builder.withParam("UnitTest", _unitTest);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTest_Back(
		IContext context,
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTest_BackBuilder(
				_unitTest,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTest_ResetBuilder(
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTest_Reset");
		builder = builder.withParam("UnitTest", _unitTest);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTest_Reset(
		IContext context,
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTest_ResetBuilder(
				_unitTest,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTest_RunBuilder(
		unittesting.proxies.UnitTest _unitTestRun,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTest_Run");
		builder = builder.withParam("UnitTestRun", _unitTestRun);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTest_Run(
		IContext context,
		unittesting.proxies.UnitTest _unitTestRun,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTest_RunBuilder(
				_unitTestRun,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTest_SelectBuilder(
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTest_Select");
		builder = builder.withParam("UnitTest", _unitTest);
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTest_Select(
		IContext context,
		unittesting.proxies.UnitTest _unitTest,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTest_SelectBuilder(
				_unitTest,
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_Filter_FailedBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_Filter_Failed");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_Filter_Failed(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_Filter_FailedBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_Filter_NotRunBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_Filter_NotRun");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_Filter_NotRun(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_Filter_NotRunBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_Filter_PassedBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_Filter_Passed");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_Filter_Passed(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_Filter_PassedBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_ResetAllBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_ResetAll");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_ResetAll(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_ResetAllBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_RunAllBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_RunAll");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_RunAll(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_RunAllBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UnitTestView_TestSuite_CloseBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ACT_UnitTestView_TestSuite_Close");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void aCT_UnitTestView_TestSuite_Close(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		aCT_UnitTestView_TestSuite_CloseBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assertTrue1Builder(
		boolean _valueToAssert
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.AssertTrue1");
		builder = builder.withParam("ValueToAssert", _valueToAssert);
		return builder;
	}

	public static void assertTrue1(
		IContext context,
		boolean _valueToAssert
	)
	{
		assertTrue1Builder(
				_valueToAssert
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assertTrue2Builder(
		boolean _valueToAssert,
		java.lang.String _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.AssertTrue2");
		builder = builder.withParam("ValueToAssert", _valueToAssert);
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static void assertTrue2(
		IContext context,
		boolean _valueToAssert,
		java.lang.String _message
	)
	{
		assertTrue2Builder(
				_valueToAssert,
				_message
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assertUsingExpressionBuilder(
		java.lang.String _name,
		boolean _expression,
		java.lang.String _failureMessage,
		boolean _stopOnFailure
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.AssertUsingExpression");
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("Expression", _expression);
		builder = builder.withParam("FailureMessage", _failureMessage);
		builder = builder.withParam("StopOnFailure", _stopOnFailure);
		return builder;
	}

	public static void assertUsingExpression(
		IContext context,
		java.lang.String _name,
		boolean _expression,
		java.lang.String _failureMessage,
		boolean _stopOnFailure
	)
	{
		assertUsingExpressionBuilder(
				_name,
				_expression,
				_failureMessage,
				_stopOnFailure
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_UnitTestView_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.DS_UnitTestView_Create");
		return builder;
	}

	public static unittesting.proxies.UnitTestView dS_UnitTestView_Create(IContext context)
	{
		Object result = dS_UnitTestView_CreateBuilder().execute(context);
		return result == null ? null : unittesting.proxies.UnitTestView.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_TestSuite_RollbackBuilder(
		unittesting.proxies.TestSuite _testSuite
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.OCH_TestSuite_Rollback");
		builder = builder.withParam("TestSuite", _testSuite);
		return builder;
	}

	public static void oCH_TestSuite_Rollback(
		IContext context,
		unittesting.proxies.TestSuite _testSuite
	)
	{
		oCH_TestSuite_RollbackBuilder(
				_testSuite
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder reportStepBuilder(
		java.lang.String _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.ReportStep");
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static void reportStep(
		IContext context,
		java.lang.String _message
	)
	{
		reportStepBuilder(
				_message
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder setupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.Setup");
		return builder;
	}

	public static void setup(IContext context)
	{
		setupBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder startupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.Startup");
		return builder;
	}

	public static boolean startup(IContext context)
	{
		Object result = startupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_TestSuite_ResetBuilder(
		unittesting.proxies.TestSuite _testSuite
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.SUB_TestSuite_Reset");
		builder = builder.withParam("TestSuite", _testSuite);
		return builder;
	}

	public static void sUB_TestSuite_Reset(
		IContext context,
		unittesting.proxies.TestSuite _testSuite
	)
	{
		sUB_TestSuite_ResetBuilder(
				_testSuite
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UnitTestView_Filter_ResetAllBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.SUB_UnitTestView_Filter_ResetAll");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void sUB_UnitTestView_Filter_ResetAll(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		sUB_UnitTestView_Filter_ResetAllBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UnitTestView_ResetSelectionBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.SUB_UnitTestView_ResetSelection");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void sUB_UnitTestView_ResetSelection(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		sUB_UnitTestView_ResetSelectionBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UnitTestView_UpdateCountersBuilder(
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.SUB_UnitTestView_UpdateCounters");
		builder = builder.withParam("UnitTestView", _unitTestView);
		return builder;
	}

	public static void sUB_UnitTestView_UpdateCounters(
		IContext context,
		unittesting.proxies.UnitTestView _unitTestView
	)
	{
		sUB_UnitTestView_UpdateCountersBuilder(
				_unitTestView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tearDownBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.TearDown");
		return builder;
	}

	public static void tearDown(IContext context)
	{
		tearDownBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tEST_WithSingleAssertionBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.TEST_WithSingleAssertion");
		return builder;
	}

	public static void tEST_WithSingleAssertion(IContext context)
	{
		tEST_WithSingleAssertionBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder unitTestOverviewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UnitTestOverview");
		return builder;
	}

	public static void unitTestOverview(IContext context)
	{
		unitTestOverviewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_WithErrorHandlingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UT_WithErrorHandling");
		return builder;
	}

	public static boolean uT_WithErrorHandling(IContext context)
	{
		Object result = uT_WithErrorHandlingBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_WithMultipleAssertionsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UT_WithMultipleAssertions");
		return builder;
	}

	public static void uT_WithMultipleAssertions(IContext context)
	{
		uT_WithMultipleAssertionsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_WithoutReturnValueBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UT_WithoutReturnValue");
		return builder;
	}

	public static void uT_WithoutReturnValue(IContext context)
	{
		uT_WithoutReturnValueBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_WithReturnValueBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UT_WithReturnValue");
		return builder;
	}

	public static boolean uT_WithReturnValue(IContext context)
	{
		Object result = uT_WithReturnValueBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_WithUnitTestContextBuilder(
		unittesting.proxies.UnitTestContext _unitTestContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UnitTesting.UT_WithUnitTestContext");
		builder = builder.withParam("UnitTestContext", _unitTestContext);
		return builder;
	}

	public static void uT_WithUnitTestContext(
		IContext context,
		unittesting.proxies.UnitTestContext _unitTestContext
	)
	{
		uT_WithUnitTestContextBuilder(
				_unitTestContext
			)
			.execute(context);
	}
}
