// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_LoadSample1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_LoadSample1");
		return builder;
	}

	public static void aCT_LoadSample1(IContext context)
	{
		aCT_LoadSample1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_LoadSample2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_LoadSample2");
		return builder;
	}

	public static void aCT_LoadSample2(IContext context)
	{
		aCT_LoadSample2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_StartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ASU_Startup");
		return builder;
	}

	public static boolean aSU_Startup(IContext context)
	{
		Object result = aSU_StartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tearDownBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.TearDown");
		return builder;
	}

	public static void tearDown(IContext context)
	{
		tearDownBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_ExtSample1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.UT_ExtSample1");
		return builder;
	}

	public static void uT_ExtSample1(IContext context)
	{
		uT_ExtSample1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_ExtSample1_2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.UT_ExtSample1_2");
		return builder;
	}

	public static void uT_ExtSample1_2(IContext context)
	{
		uT_ExtSample1_2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_ExtSample1_3Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.UT_ExtSample1_3");
		return builder;
	}

	public static void uT_ExtSample1_3(IContext context)
	{
		uT_ExtSample1_3Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder uT_ExtSample2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.UT_ExtSample2");
		return builder;
	}

	public static void uT_ExtSample2(IContext context)
	{
		uT_ExtSample2Builder().execute(context);
	}
}
