// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies;

public enum ENUM_UnitTestResult
{
	_1_Running("94c18c65-872a-435d-9f3b-6f626170a1bf"),
	_2_Failed("e3c5229b-7158-4bd7-a667-024567a1a760"),
	_3_Success("483acc4d-01ac-49b9-adee-b92216334f4b");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_UnitTestResult(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
