// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies;

public class TestActivity implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testActivityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UnitTesting.TestActivity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		Message("Message"),
		TestActivity_UnitTest("UnitTesting.TestActivity_UnitTest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestActivity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestActivity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testActivityMendixObject)
	{
		if (testActivityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testActivityMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testActivityMendixObject = testActivityMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static unittesting.proxies.TestActivity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("UnitTesting.AssertionActivity")) {
			return unittesting.proxies.AssertionActivity.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("UnitTesting.EndActivity")) {
			return unittesting.proxies.EndActivity.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("UnitTesting.ExceptionActivity")) {
			return unittesting.proxies.ExceptionActivity.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("UnitTesting.StartActivity")) {
			return unittesting.proxies.StartActivity.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("UnitTesting.StepActivity")) {
			return unittesting.proxies.StepActivity.initialize(context, mendixObject);
		}
		return new unittesting.proxies.TestActivity(context, mendixObject);
	}

	public static unittesting.proxies.TestActivity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return unittesting.proxies.TestActivity.initialize(context, mendixObject);
	}

	public static java.util.List<? extends unittesting.proxies.TestActivity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> unittesting.proxies.TestActivity.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestActivity_UnitTest
	 */
	public final unittesting.proxies.UnitTest getTestActivity_UnitTest() throws com.mendix.core.CoreException
	{
		return getTestActivity_UnitTest(getContext());
	}

	/**
	 * @param context
	 * @return value of TestActivity_UnitTest
	 * @throws com.mendix.core.CoreException
	 */
	public final unittesting.proxies.UnitTest getTestActivity_UnitTest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittesting.proxies.UnitTest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestActivity_UnitTest.toString());
		if (identifier != null) {
			result = unittesting.proxies.UnitTest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestActivity_UnitTest
	 * @param testactivity_unittest
	 */
	public final void setTestActivity_UnitTest(unittesting.proxies.UnitTest testactivity_unittest)
	{
		setTestActivity_UnitTest(getContext(), testactivity_unittest);
	}

	/**
	 * Set value of TestActivity_UnitTest
	 * @param context
	 * @param testactivity_unittest
	 */
	public final void setTestActivity_UnitTest(com.mendix.systemwideinterfaces.core.IContext context, unittesting.proxies.UnitTest testactivity_unittest)
	{
		if (testactivity_unittest == null) {
			getMendixObject().setValue(context, MemberNames.TestActivity_UnitTest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestActivity_UnitTest.toString(), testactivity_unittest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testActivityMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final unittesting.proxies.TestActivity that = (unittesting.proxies.TestActivity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
