// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittesting.proxies;

public class UnitTestView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject unitTestViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UnitTesting.UnitTestView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsEnabled("IsEnabled"),
		IsInitialized("IsInitialized"),
		TestCount("TestCount"),
		TestPassedCount("TestPassedCount"),
		TestFailedCount("TestFailedCount"),
		ShowPassed("ShowPassed"),
		ShowFailed("ShowFailed"),
		ShowNotRun("ShowNotRun"),
		UnitTestView_UnitTest("UnitTesting.UnitTestView_UnitTest"),
		UnitTestView_TestSuite("UnitTesting.UnitTestView_TestSuite");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UnitTestView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UnitTestView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject unitTestViewMendixObject)
	{
		if (unitTestViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!unitTestViewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.unitTestViewMendixObject = unitTestViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static unittesting.proxies.UnitTestView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new unittesting.proxies.UnitTestView(context, mendixObject);
	}

	public static unittesting.proxies.UnitTestView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return unittesting.proxies.UnitTestView.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled()
	{
		return getIsEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnabled.toString());
	}

	/**
	 * Set value of IsEnabled
	 * @param isenabled
	 */
	public final void setIsEnabled(java.lang.Boolean isenabled)
	{
		setIsEnabled(getContext(), isenabled);
	}

	/**
	 * Set value of IsEnabled
	 * @param context
	 * @param isenabled
	 */
	public final void setIsEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsEnabled.toString(), isenabled);
	}

	/**
	 * @return value of IsInitialized
	 */
	public final java.lang.Boolean getIsInitialized()
	{
		return getIsInitialized(getContext());
	}

	/**
	 * @param context
	 * @return value of IsInitialized
	 */
	public final java.lang.Boolean getIsInitialized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsInitialized.toString());
	}

	/**
	 * Set value of IsInitialized
	 * @param isinitialized
	 */
	public final void setIsInitialized(java.lang.Boolean isinitialized)
	{
		setIsInitialized(getContext(), isinitialized);
	}

	/**
	 * Set value of IsInitialized
	 * @param context
	 * @param isinitialized
	 */
	public final void setIsInitialized(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isinitialized)
	{
		getMendixObject().setValue(context, MemberNames.IsInitialized.toString(), isinitialized);
	}

	/**
	 * @return value of TestCount
	 */
	public final java.lang.Integer getTestCount()
	{
		return getTestCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TestCount
	 */
	public final java.lang.Integer getTestCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestCount.toString());
	}

	/**
	 * Set value of TestCount
	 * @param testcount
	 */
	public final void setTestCount(java.lang.Integer testcount)
	{
		setTestCount(getContext(), testcount);
	}

	/**
	 * Set value of TestCount
	 * @param context
	 * @param testcount
	 */
	public final void setTestCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testcount)
	{
		getMendixObject().setValue(context, MemberNames.TestCount.toString(), testcount);
	}

	/**
	 * @return value of TestPassedCount
	 */
	public final java.lang.Integer getTestPassedCount()
	{
		return getTestPassedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TestPassedCount
	 */
	public final java.lang.Integer getTestPassedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestPassedCount.toString());
	}

	/**
	 * Set value of TestPassedCount
	 * @param testpassedcount
	 */
	public final void setTestPassedCount(java.lang.Integer testpassedcount)
	{
		setTestPassedCount(getContext(), testpassedcount);
	}

	/**
	 * Set value of TestPassedCount
	 * @param context
	 * @param testpassedcount
	 */
	public final void setTestPassedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testpassedcount)
	{
		getMendixObject().setValue(context, MemberNames.TestPassedCount.toString(), testpassedcount);
	}

	/**
	 * @return value of TestFailedCount
	 */
	public final java.lang.Integer getTestFailedCount()
	{
		return getTestFailedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TestFailedCount
	 */
	public final java.lang.Integer getTestFailedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TestFailedCount.toString());
	}

	/**
	 * Set value of TestFailedCount
	 * @param testfailedcount
	 */
	public final void setTestFailedCount(java.lang.Integer testfailedcount)
	{
		setTestFailedCount(getContext(), testfailedcount);
	}

	/**
	 * Set value of TestFailedCount
	 * @param context
	 * @param testfailedcount
	 */
	public final void setTestFailedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer testfailedcount)
	{
		getMendixObject().setValue(context, MemberNames.TestFailedCount.toString(), testfailedcount);
	}

	/**
	 * @return value of ShowPassed
	 */
	public final java.lang.Boolean getShowPassed()
	{
		return getShowPassed(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowPassed
	 */
	public final java.lang.Boolean getShowPassed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowPassed.toString());
	}

	/**
	 * Set value of ShowPassed
	 * @param showpassed
	 */
	public final void setShowPassed(java.lang.Boolean showpassed)
	{
		setShowPassed(getContext(), showpassed);
	}

	/**
	 * Set value of ShowPassed
	 * @param context
	 * @param showpassed
	 */
	public final void setShowPassed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showpassed)
	{
		getMendixObject().setValue(context, MemberNames.ShowPassed.toString(), showpassed);
	}

	/**
	 * @return value of ShowFailed
	 */
	public final java.lang.Boolean getShowFailed()
	{
		return getShowFailed(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowFailed
	 */
	public final java.lang.Boolean getShowFailed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowFailed.toString());
	}

	/**
	 * Set value of ShowFailed
	 * @param showfailed
	 */
	public final void setShowFailed(java.lang.Boolean showfailed)
	{
		setShowFailed(getContext(), showfailed);
	}

	/**
	 * Set value of ShowFailed
	 * @param context
	 * @param showfailed
	 */
	public final void setShowFailed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showfailed)
	{
		getMendixObject().setValue(context, MemberNames.ShowFailed.toString(), showfailed);
	}

	/**
	 * @return value of ShowNotRun
	 */
	public final java.lang.Boolean getShowNotRun()
	{
		return getShowNotRun(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowNotRun
	 */
	public final java.lang.Boolean getShowNotRun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowNotRun.toString());
	}

	/**
	 * Set value of ShowNotRun
	 * @param shownotrun
	 */
	public final void setShowNotRun(java.lang.Boolean shownotrun)
	{
		setShowNotRun(getContext(), shownotrun);
	}

	/**
	 * Set value of ShowNotRun
	 * @param context
	 * @param shownotrun
	 */
	public final void setShowNotRun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownotrun)
	{
		getMendixObject().setValue(context, MemberNames.ShowNotRun.toString(), shownotrun);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UnitTestView_UnitTest
	 */
	public final unittesting.proxies.UnitTest getUnitTestView_UnitTest() throws com.mendix.core.CoreException
	{
		return getUnitTestView_UnitTest(getContext());
	}

	/**
	 * @param context
	 * @return value of UnitTestView_UnitTest
	 * @throws com.mendix.core.CoreException
	 */
	public final unittesting.proxies.UnitTest getUnitTestView_UnitTest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittesting.proxies.UnitTest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UnitTestView_UnitTest.toString());
		if (identifier != null) {
			result = unittesting.proxies.UnitTest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UnitTestView_UnitTest
	 * @param unittestview_unittest
	 */
	public final void setUnitTestView_UnitTest(unittesting.proxies.UnitTest unittestview_unittest)
	{
		setUnitTestView_UnitTest(getContext(), unittestview_unittest);
	}

	/**
	 * Set value of UnitTestView_UnitTest
	 * @param context
	 * @param unittestview_unittest
	 */
	public final void setUnitTestView_UnitTest(com.mendix.systemwideinterfaces.core.IContext context, unittesting.proxies.UnitTest unittestview_unittest)
	{
		if (unittestview_unittest == null) {
			getMendixObject().setValue(context, MemberNames.UnitTestView_UnitTest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UnitTestView_UnitTest.toString(), unittestview_unittest.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UnitTestView_TestSuite
	 */
	public final unittesting.proxies.TestSuite getUnitTestView_TestSuite() throws com.mendix.core.CoreException
	{
		return getUnitTestView_TestSuite(getContext());
	}

	/**
	 * @param context
	 * @return value of UnitTestView_TestSuite
	 * @throws com.mendix.core.CoreException
	 */
	public final unittesting.proxies.TestSuite getUnitTestView_TestSuite(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittesting.proxies.TestSuite result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UnitTestView_TestSuite.toString());
		if (identifier != null) {
			result = unittesting.proxies.TestSuite.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UnitTestView_TestSuite
	 * @param unittestview_testsuite
	 */
	public final void setUnitTestView_TestSuite(unittesting.proxies.TestSuite unittestview_testsuite)
	{
		setUnitTestView_TestSuite(getContext(), unittestview_testsuite);
	}

	/**
	 * Set value of UnitTestView_TestSuite
	 * @param context
	 * @param unittestview_testsuite
	 */
	public final void setUnitTestView_TestSuite(com.mendix.systemwideinterfaces.core.IContext context, unittesting.proxies.TestSuite unittestview_testsuite)
	{
		if (unittestview_testsuite == null) {
			getMendixObject().setValue(context, MemberNames.UnitTestView_TestSuite.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UnitTestView_TestSuite.toString(), unittestview_testsuite.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return unitTestViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final unittesting.proxies.UnitTestView that = (unittesting.proxies.UnitTestView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
